learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views
from django.urls import path

# Template tagging
app_name = 'basicapp'

urlpatterns = [
    path('other/', views.other,name='other'),
    path('relative/', views.relative,name='index'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.conf.urls import include

urlpatterns = [
    path('', views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':"Hello World",'number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
		integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Anything outside this will be inherited if you extend -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% load my_extras %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is an example of template inheritance!</h2>
    <hr>
    <h1>Filters</h1>
    <h1>{{ text|cutter:'l' }}</h1>
    <h1>{{ number|add:'69' }}</h1>
  {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basicapp:other' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Link to Admin</a>
    <a href="{% url 'index' %}">Link to Index</a>
  </body>
</html>